export interface DeptInfo {
  college: string;
  notice: string | null;
}

export const DEPT_LINKS: Record<string, DeptInfo> = {
  "국어국문학과": { college: "인문대학", notice: "https://bkorea.pusan.ac.kr/bkorea/3346/subview.do" },
  "중어중문학과": { college: "인문대학", notice: "https://china.pusan.ac.kr/china/2652/subview.do" },
  "일어일문학과": { college: "인문대학", notice: "https://japan.pusan.ac.kr/japan/8796/subview.do" },
  "노어노문학과": { college: "인문대학", notice: "https://russia.pusan.ac.kr/russia/2316/subview.do" },
  "언어정보학과": { college: "인문대학", notice: "https://linguistics.pusan.ac.kr/linguistics/8764/subview.do" },
  "사학과": { college: "인문대학", notice: "https://history.pusan.ac.kr/history/6500/subview.do" },
  "철학과": { college: "인문대학", notice: "https://philosophy.pusan.ac.kr/philosophy/11291/subview.do" },
  "행정학과": { college: "사회과학대학", notice: "https://pub-adm.pusan.ac.kr/pub-adm/13892/subview.do" },
  "정치외교학과": { college: "사회과학대학", notice: "https://polsci.pusan.ac.kr/polsci/7498/subview.do" },
  "사회복지학과": { college: "사회과학대학", notice: "https://swf.pusan.ac.kr/swf/13623/subview.do" },
  "사회학과": { college: "사회과학대학", notice: "https://soc.pusan.ac.kr/soc/9355/subview.do" },
  "심리학과": { college: "사회과학대학", notice: "https://psy.pusan.ac.kr/psy/2366/subview.do" },
  "문헌정보학과": { college: "사회과학대학", notice: "https://lais.pusan.ac.kr/lais/9201/subview.do" },
  "미디어커뮤니케이션학과": { college: "사회과학대학", notice: "https://comm.pusan.ac.kr/comm/12531/subview.do" },
  "수학과": { college: "자연과학대학", notice: "https://math.pusan.ac.kr/math/11218/subview.do" },
  "통계학과": { college: "자연과학대학", notice: "https://stat.pusan.ac.kr/stat/4227/subview.do" },
  "물리학과": { college: "자연과학대학", notice: "https://phys.pusan.ac.kr/phys/12920/subview.do" },
  "화학과": { college: "자연과학대학", notice: "https://chem.pusan.ac.kr/chem/6291/subview.do" },
  "생명과학과": { college: "자연과학대학", notice: "https://biology.pusan.ac.kr/biology/5536/subview.do" },
  "분자생물학과": { college: "자연과학대학", notice: "https://molbiology.pusan.ac.kr/molbiology/6788/subview.do" },
  "미생물학과": { college: "자연과학대학", notice: "https://microbio.pusan.ac.kr/microbio/10800/subview.do" },
  "지질환경과학과": { college: "자연과학대학", notice: "https://geology.pusan.ac.kr/geology/3212/subview.do" },
  "대기환경과학과": { college: "자연과학대학", notice: "https://atmos.pusan.ac.kr/atmos/4950/subview.do" },
  "해양학과": { college: "자연과학대학", notice: "https://ocean.pusan.ac.kr/ocean/12798/subview.do" },
  "기계공학부": { college: "공과대학", notice: "https://me.pusan.ac.kr/new/sub05/sub01_01.php" },
  "고분자공학과": { college: "공과대학", notice: "https://polymer.pusan.ac.kr/polymer/3892/subview.do" },
  "유기소재시스템공학과": { college: "공과대학", notice: "https://omse.pusan.ac.kr/omse/9153/subview.do" },
  "화공생명공학과": { college: "공과대학", notice: "https://chemeng.pusan.ac.kr/chemeng/6432/subview.do" },
  "환경공학과": { college: "공과대학", notice: "https://pnuenv.pusan.ac.kr/pnuenv/5930/subview.do" },
  "전자공학전공": { college: "전기전자공학부", notice: "https://ee.pusan.ac.kr/ee/5204/subview.do" },
  "전기공학전공": { college: "전기전자공학부", notice: "https://eec.pusan.ac.kr/eehome/3028/subview.do" },
  "반도체공학전공": { college: "전기전자공학부", notice: "https://semi.pusan.ac.kr/semi/2869/subview.do" },
  "조선해양공학과": { college: "공과대학", notice: "https://naoe.pusan.ac.kr/naoe/14346/subview.do" },
  "재료공학부": { college: "공과대학", notice: "https://mse.pusan.ac.kr/mse/38585/subview.do" },
  "산업공학과": { college: "공과대학", notice: "https://ie.pusan.ac.kr/ie/5850/subview.do" },
  "항공우주공학과": { college: "공과대학", notice: "https://aerospace.pusan.ac.kr/aerospace/1455/subview.do" },
  "건축공학과": { college: "공과대학", notice: "https://archieng.pusan.ac.kr/archieng/8424/subview.do" },
  "건축학과": { college: "공과대학", notice: "https://archi.pusan.ac.kr/archi/6175/subview.do" },
  "도시공학과": { college: "공과대학", notice: "https://urban.pusan.ac.kr/urban/4184/subview.do" },
  "사회기반시스템공학과": { college: "공과대학", notice: "https://civil.pusan.ac.kr/civil/10880/subview.do" },
  "미래도시건축환경융합전공": { college: "공과대학", notice: "https://fu.pusan.ac.kr/fu/4474/subview.do" },
  "스마트시티전공": { college: "공과대학", notice: null },
  "국어교육과": { college: "사범대학", notice: "https://koredu.pusan.ac.kr/koredu/26185/subview.do" },
  "영어교육과": { college: "사범대학", notice: "https://englishedu.pusan.ac.kr/englishedupnu/1285/subview.do" },
  "독어교육과": { college: "사범대학", notice: "https://geredu.pusan.ac.kr/geredu/1772/subview.do" },
  "불어교육과": { college: "사범대학", notice: "https://fredu.pusan.ac.kr/fredu/13238/subview.do" },
  "교육학과": { college: "사범대학", notice: "https://ed.pusan.ac.kr/ed/2957/subview.do" },
  "유아교육과": { college: "사범대학", notice: "https://child.pusan.ac.kr/child/4527/subview.do" },
  "특수교육과": { college: "사범대학", notice: "https://special.pusan.ac.kr/special/1195/subview.do" },
  "일반사회교육과": { college: "사범대학", notice: "https://socialedu.pusan.ac.kr/socialedu/3541/subview.do" },
  "역사교육과": { college: "사범대학", notice: "https://hisedu.pusan.ac.kr/hisedu/12452/subview.do" },
  "지리교육과": { college: "사범대학", notice: "https://geoedu.pusan.ac.kr/geoedu/6041/subview.do" },
  "윤리교육과": { college: "사범대학", notice: "https://ethics.pusan.ac.kr/ethics/4781/subview.do" },
  "수학교육과": { college: "사범대학", notice: "https://mathedu.pusan.ac.kr/mathedu/9094/subview.do" },
  "물리교육과": { college: "사범대학", notice: "https://physedu.pusan.ac.kr/physedu/11861/subview.do" },
  "화학교육과": { college: "사범대학", notice: "https://chemedu.pusan.ac.kr/chemedu/6345/subview.do" },
  "생물교육과": { college: "사범대학", notice: "https://edubio.pusan.ac.kr/edubio/2968/subview.do" },
  "지구과학교육과": { college: "사범대학", notice: "https://earth.pusan.ac.kr/earth/1245/subview.do" },
  "체육교육과": { college: "사범대학", notice: "https://physicaledu.pusan.ac.kr/physicaledu/7345/subview.do" },
  "무역학부": { college: "경제통상대학", notice: "https://pnutrade.pusan.ac.kr/pnutrade/2560/subview.do" },
  "경제학부": { college: "경제통상대학", notice: "https://pnuecon.pusan.ac.kr/pnuecon/4872/subview.do" },
  "관광컨벤션학과": { college: "경제통상대학", notice: "https://convention.pusan.ac.kr/convention/2097/subview.do" },
  "국제학부": { college: "경제통상대학", notice: "https://pnudgs.com/board/bbs/board.php?bo_table=Notice" },
  "공공정책학부": { college: "경제통상대학", notice: "https://ppm.pusan.ac.kr/ppm/9468/subview.do" },
  "경영학과": { college: "경영대학", notice: "https://biz.pusan.ac.kr/biz/8941/subview.do" },
  "약학전공": { college: "약학대학", notice: "https://pharmacy.pusan.ac.kr/pharmacy/5754/subview.do" },
  "제약학전공": { college: "약학대학", notice: "https://pharmacy.pusan.ac.kr/pharmacy/5754/subview.do" },
  "아동가족학과": { college: "생활과학대학", notice: "https://cdfs.pusan.ac.kr/cdfs/1556/subview.do" },
  "의류학과": { college: "생활과학대학", notice: "https://fashion.pusan.ac.kr/fashion/8612/subview.do" },
  "식품영양학과": { college: "생활과학대학", notice: "https://fsn.pusan.ac.kr/fsn/5715/subview.do" },
  "실내환경디자인학과": { college: "생활과학대학", notice: "https://hid.pusan.ac.kr/hid/10653/subview.do" },
  "스포츠과학과": { college: "생활과학대학", notice: "https://sportscience.pusan.ac.kr/sportscience/3107/subview.do" },
  "음악학과": { college: "예술대학", notice: "https://music.pusan.ac.kr/music/11763/subview.do" },
  "한국음악학과": { college: "예술대학", notice: "https://gukak.pusan.ac.kr/gukak/10687/subview.do" },
  "미술학과": { college: "예술대학", notice: "https://pnuart.pusan.ac.kr/pnuart/13595/subview.do" },
  "조형학과": { college: "예술대학", notice: "https://plarts.pusan.ac.kr/plarts/13690/subview.do" },
  "디자인학과": { college: "예술대학", notice: "https://design.pusan.ac.kr/design/5370/subview.do" },
  "무용학과": { college: "예술대학", notice: "https://dance.pusan.ac.kr/dance/12636/subview.do" },
  "예술문화영상학과": { college: "예술대학", notice: "https://artimage.pusan.ac.kr/artimage/8081/subview.do" },
  "나노메카트로닉스공학과": { college: "나노과학기술대학", notice: "https://nanomecha.pusan.ac.kr/nanomecha/10848/subview.do" },
  "나노에너지공학과": { college: "나노과학기술대학", notice: "https://energy.pusan.ac.kr/energy/5109/subview.do" },
  "광메카트로닉스공학과": { college: "나노과학기술대학", notice: "https://ome.pusan.ac.kr/ome/9051/subview.do" },
  "식물생명과학과": { college: "생명자원과학대학", notice: "https://plant.pusan.ac.kr/plant/7376/subview.do" },
  "동물생명자원과학과": { college: "생명자원과학대학", notice: "https://animal.pusan.ac.kr/animal/3252/subview.do" },
  "식품공학과": { college: "생명자원과학대학", notice: "https://fst.pusan.ac.kr/fst/10298/subview.do" },
  "생명환경화학과": { college: "생명자원과학대학", notice: "https://pnu-lseb.pusan.ac.kr/pnu-lseb/5505/subview.do" },
  "바이오소재과학과": { college: "생명자원과학대학", notice: "https://bm.pusan.ac.kr/bm/13191/subview.do" },
  "바이오산업기계공학과": { college: "생명자원과학대학", notice: "https://bime.pusan.ac.kr/bime/8508/subview.do" },
  "조경학과": { college: "생명자원과학대학", notice: "https://la.pusan.ac.kr/la/5884/subview.do" },
  "식품자원경제학과": { college: "생명자원과학대학", notice: "https://agecon.pusan.ac.kr/agecon/13100/subview.do" },
  "IT응용과학과": { college: "생명자원과학대학", notice: "https://ite.pusan.ac.kr/ite/13812/subview.do" },
  "바이오환경에너지학과": { college: "생명자원과학대학", notice: "https://bee.pusan.ac.kr/bee/13472/subview.do" },
  "간호학과": { college: "간호대학", notice: "https://nursing.pusan.ac.kr/nursing/10427/subview.do" },
  "의예과": { college: "의과대학", notice: "https://medicine.pusan.ac.kr/medicine/14487/subview.do" },
  "의학과": { college: "의과대학", notice: "https://medicine.pusan.ac.kr/medicine/14492/subview.do" },
  "컴퓨터공학전공": { college: "정보의생명공학대학", notice: "https://cse.pusan.ac.kr/cse/14221/subview.do" },
  "인공지능전공": { college: "정보의생명공학대학", notice: "https://cse.pusan.ac.kr/cse/14221/subview.do" },
  "디자인테크놀로지전공": { college: "정보의생명공학대학", notice: "https://inter.pusan.ac.kr/designtech/15921/subview.do" },
  "의생명융합공학부": { college: "정보의생명공학대학", notice: "https://bce.pusan.ac.kr/bce/5008/subview.do" },
  "정보의생명공학자율전공": { college: "정보의생명공학대학", notice: null },
  "자유전공학부": { college: "학부대학", notice: "https://liberal.pusan.ac.kr/liberal/8696/subview.do" },
  "글로벌자유전공학부": { college: "학부대학", notice: "https://global.pusan.ac.kr/global/10517/subview.do" },
  "첨단융합학부 미래에너지전공": { college: "학부대학", notice: "https://energy.pusan.ac.kr/energy/5109/subview.do" },
  "첨단융합학부 나노소자첨단제조전공": { college: "학부대학", notice: "https://nanomecha.pusan.ac.kr/nanomecha/10848/subview.do" },
  "첨단융합학부 광메카트로닉스공학전공": { college: "학부대학", notice: "https://ome.pusan.ac.kr/ome/9051/subview.do" },
  "첨단융합학부 AI융합계산과학전공": { college: "학부대학", notice: null },
  "응용생명융합학부 그린바이오과학전공": { college: "학부대학", notice: null },
  "응용생명융합학부 생명자원시스템공학전공": { college: "학부대학", notice: "https://brse.pusan.ac.kr/brse/14763/subview.do" },
};

export function getDeptList(): Array<{ name: string; college: string }> {
  return Object.entries(DEPT_LINKS)
    .map(([name, info]) => ({ name, college: info.college }))
    .sort((a, b) => a.name.localeCompare(b.name, 'ko', { sensitivity: 'base' }));
}
